### ISSUE TITLE
get_* methods returning single dict on single-object returns (should be dict within list)

### ISSUE THREAD

**Issue by subnomo** [osuosl/pymesync#131] opened 2016-04-21 20:45 UTC
When it's provided with a username, it should return a single dict. Instead, it returns a list containing a single dict.

This should be a simple fix, I'll create a PR in a sec.

**Comment by matthewrsj** [comment] 2016-04-22 15:29
The same is true for `get_activities`, `get_times`, and `get_projects`. The bug is the inconsistency between the source code, the test code, and the ambiguity in the docs.

We need to decide on an approach. If I recall correctly, the idea was for methods that *can* return more than one object return a list of objects, even if that list contains only **zero or one** object, and even if the user specified a `username`, `slug`, or `uuid`. If this holds true, the source code is incorrect and the docs are ambiguous, but the test mode returns are correct.

The reason for this was so the frontend logic could remain the same regardless of the number of objects returned.

So yes, this is a bug, but it is undefined where the bug actually lies. I will talk with TimeSync's frontend developers today to see what everyone prefers.

@Kennric @subnomo @aaroncohen73

**Comment by aaroncohen73** [comment] 2016-04-22 21:38
I think that it would be easier and simpler to keep it how it was (Always returning a list of dicts). It's simpler and more consistent. For example, the climesync function print_json has to check whether or not the thing that pymesync returned is a list or a dict, and the way that it prints those two things are basically the same.

**Comment by matthewrsj** [comment] 2016-04-25 15:19
Forgot to comment again a few days ago, but pymesync actually does return a list even for zero or one objects, since it returns the structure returned by the API. The bug here is that the docs are ambiguous.

**Comment by subnomo** [comment] 2016-04-27 18:51
@matthewrsj I'm still getting a single dict when only one object is returned. Here is some sample code,

```python
import pymesync

ts = pymesync.TimeSync(baseurl='<STAGING URL>')
ts.authenticate(username='test', password='test', auth_type='password')

print ts.get_users()
print ts.get_users(username='admin')
```
and its output
```
[{u'username': u'admin', u'display_name': u'root', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': None, u'site_manager': True, u'meta': u'Root user. Created by setup script. Use to create other users.', u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': None}, ...]

{u'username': u'admin', u'display_name': u'root', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': None, u'site_manager': True, u'meta': u'Root user. Created by setup script. Use to create other users.', u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': None}
```

**Comment by matthewrsj** [comment] 2016-04-29 17:23
Good catch. Can you look into this @subnomo? Ideal behavior is that all get_* methods return a dict within a list, even with zero or one dict.

Without looking too closely at the pymesync source, it appears that TimeSync is returning an object not contained in a list for single-object returns, which is not expected behavior. If that is the case, confirm that the API specifies object-within-a-list returns and file a bug with timesync-node.

If the bug exists in pymesync, please locate and fix.

Thank you.

**Comment by matthewrsj** [comment] 2016-05-02 18:07
This was mistakenly closed by #133

**Comment by subnomo** [comment] 2016-05-10 20:21
@matthewrsj It seems that returning a single object not within a list is the correct behavior (according to the API). I agree that it would make more sense to always return a list.

The question is:
- Should pymesync be convenient and always return a list?

*or*

- Should pymesync adhere to the API spec? (My choice)

**Comment by ElijahCaine** [comment] 2016-05-11 17:46
Let me know if this is incorrect, but this is generally what option A would look like *in the code*:
```python
for element in get_foo(param1, param2):
    # do thing
    # etc...
```

And this is what option B would look like *in the code*:
```python
val = get_foo(param1, param2)
if type(val) == list:
    for element in val:
      # do thing
      # etc
else:
    # do thing
    # etc
```

I am all for standardizing with the API, just wanted to make sure y'all thought about the programming implications.

![I have no strong feelings one way or another](http://s2.quickmeme.com/img/0e/0e5fd0091333b94cbde2f764970076238119d6a807e73edf1e4b86c9e85c2383.jpg)

... but you might.

**Comment by matthewrsj** [comment] 2016-05-13 20:11
Sorry, forgot about this.

I definitely prefer @ElijahCaine's option A for the simple reason that pymesync needs to make frontend development for TimeSync easy. We should do that type check in pymesync, not flask. If the API is updated to (what I believe to be) the correct way of doing things, it shouldn't break pymesync code (either way actually, but it is much cleaner for this check to live in the library).

Just one man's opinion.

**Comment by subnomo** [comment] 2016-05-17 19:42
@ElijahCaine @matthewrsj You're right, option B doesn't look too fun. I'll work on implementing A.

**Comment by ElijahCaine** [comment] 2016-05-17 20:08
@subnomo Just make sure to document this in the `pymesync` docs. Put it in a `.. warning::` because it might not be intuitive for certain schools of thought.

**Comment by subnomo** [comment] 2016-05-17 21:30
@ElijahCaine Apparently, it's already in the docs:

> This method always returns a list, even if the list contains zero or one time object.

**Comment by matthewrsj** [comment] 2016-05-17 21:32
Yeah, that's the intended behavior.

**Closed** 2016-05-19 19:05 UTC
Labels: bug, Documentation, High Priority
